### ISSUE TITLE
TypeError: MinkowskiConvolution.__init__() got an unexpected keyword argument 'has_bias'

### ISSUE THREAD

**Issue by xunfeng2zkj** [GrumpyZhou/image-matching-toolbox#32]
'has_bias' should be “bias”？

**Comment by GrumpyZhou** [comment]
I believe this is due to using different versions of MinkowskiEngine.  This repo assumes that users install environment for SparseNCNet following the official guide [INSTALL.md](https://github.com/ignacio-rocco/sparse-ncnet/blob/master/INSTALL.md). To update the SparseNCNet interfaces for newer versions, you need to raise the issue there instead of here since it is not an issue of this repo.
